### ISSUE TITLE
keys with underscore converted as blank

### ISSUE THREAD

**Issue by gistic-guob** [danielhall/json-key-casing#11]
I noticed when a key such as "LAYER_NAME" was converted to lower case it became "layer name".  Unless it was by design, I was expecting the result to be "layer_name".

**Comment by danielhall** [comment]
Hi, sorry for not getting onto this sooner! Just coming back to this lib and cleaning it up a bit.
To achieve 'layer_name', you'd need to convert to 'snake'. The library uses the node package 'case' to convert the casing, and the name of the casing you're describing on that is snake.
Thanks
